# Logo (Font Awesome Class)
# fa_logo: fa-cube
fa_logo: fa-code

# Header
menu:
  Home: /
  Archives: /archives
  # About: /about.html
  Tags: /tags
  Categories: /categories
  # Contact: /contact.html

# Default post title
default_post_title: Untitled

# Archive Date Format
archive_date_format: YYYY-MM-DD

# Comments.
comments:
  # Disqus comments
  disqus_shortname: hyunjun19-blog

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
# twitter_url: https://twitter.com/?lang=en
# facebook_url: https://www.facebook.com/
# instagram_url: https://www.instagram.com/
# dribble_url: https://dribbble.com/
github_url: https://github.com/hyunjun19
# googleplus_url: https://plus.google.com/
# behance_url: https://www.behance.net/
# fivehundredpx_url: https://500px.com/
email_url: hyunjun19@gmail.com
rss_url: \#

# Footer About Text
footer_about: "This theme was developed by <a href=\"https://github.com/klugjo\">Jonathan Klughertz</a>."

# Footer Copyright Line
footer_copyright: "@Untitled. All right reserved | Design & Hexo <a href=\"http://www.codeblocq.com/\">Jonathan Klughertz</a>"
